name: test with vitest

on:
    push:
      branches: [ main, staging ]
    pull_request:
      branches: [ main, staging ]

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    services:
      fauna:
        image: fauna/faunadb
        ports:
          - 8443:8443
          - 8084:8084
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.16
      - name: npm install, build
        run: |
          npm ci
          npm run build
          npm run lint
        env:
          NODE_ENV: 'test'
          CI: true
      - name: Run tests
        run: |
          npm run test:ci

